config/routes.rb
Rails.application.routes.draw do
  resources :restrict_emails
  resources :restrict_emails do
    collection do
      delete 'destroy_multiple'
    end
  end

  put'/multiple_delete' => 'restrict_emails#multiple_delete' 

end

app/models/restrict_email.rb
class RestrictEmail < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restrict_emails_controller.rb
class RestrictEmailsController < ApplicationController
 # before_action :set_restrict_email, only: [:show, :edit, :update, :destroy]

  # GET /restrict_emails
  # GET /restrict_emails.json
  def index
    @restrict_emails = RestrictEmail.all
  end

  # GET /restrict_emails/1
  # GET /restrict_emails/1.json
  def show
  end

  # GET /restrict_emails/new
  def new
    @restrict_email = RestrictEmail.new
  end

  # GET /restrict_emails/1/edit
  def edit
  end

  # POST /restrict_emails
  # POST /restrict_emails.json
  def create
    
    @restrict_email = RestrictEmail.new(restrict_email_params)
    email_array= params[:restrict_email][:blocked_email].split(',')
    new_hash=[]
    email_array.map{|email_string| new_hash.push({blocked_email:email_string})}
    RestrictEmail.create(new_hash)
    
    redirect_to restrict_emails_url
    # respond_to do |format|
    #   if @restrict_email.save
    #     format.html { redirect_to @restrict_email, notice: 'Restrict email was successfully created.' }
    #     format.json { render :show, status: :created, location: @restrict_email }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @restrict_email.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /restrict_emails/1
  # PATCH/PUT /restrict_emails/1.json

  def destroy_multiple
  respond_to do |format|
    format.html { redirect_to blog_posts_path }
    format.json { head :no_content }
  end

end


  def update
    respond_to do |format|
      if @restrict_email.update(restrict_email_params)
        format.html { redirect_to @restrict_email, notice: 'Restrict email was successfully updated.' }
        format.json { render :show, status: :ok, location: @restrict_email }
      else
        format.html { render :edit }
        format.json { render json: @restrict_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restrict_emails/1
  # DELETE /restrict_emails/1.json
  def destroy
map_ids=params[:blocked_email].map{|id| id.split('-')[1].to_i} 
 RestrictEmail.delete_all(["id in (?)", map_ids])
    respond_to do |format|
      format.html { redirect_to restrict_emails_url, notice: 'Restrict email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restrict_email
      @restrict_email = RestrictEmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restrict_email_params
      params.require(:restrict_email).permit(:blocked_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restrict_emails_helper.rb
module RestrictEmailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DummyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/bootstrap-tokenfield.min.js" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tokenfield/0.12.0/css/bootstrap-tokenfield.min.css"  crossorigin="anonymous">
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/restrict_emails/_form.html.erb
<%= form_for(@restrict_email) do |f| %>
  <% if @restrict_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restrict_email.errors.count, "error") %> prohibited this restrict_email from being saved:</h2>

      <ul>
      <% @restrict_email.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restrict_emails/edit.html.erb
<h1>Editing Restrict Email</h1>

<%= render 'form' %>

<%= link_to 'Show', @restrict_email %> |
<%= link_to 'Back', restrict_emails_path %>

app/views/restrict_emails/index.html.erb
<p id="notice"><%= notice %></p>

<%=form_tag restrict_emails_path, :html => {:method => :post} do %>
 <textarea name="restrict_email[blocked_email]" id="restrict_email_blocked_email" class="form-control no-border" required="true"></textarea>
  <%= submit_tag "submit", class: "btn btn-primary pull-right" %>
<%end%>

<h1>Listing Restrict Emails</h1>
<%unless @restrict_emails.blank?%>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%=form_tag  destroy_multiple_restrict_emails_path  ,id:'delete-form' ,method: :delete do%>
    <% @restrict_emails.each do |restrict_email| %>
      <tr>
       <td><%=check_box_tag "blocked_email[]","#{restrict_email.blocked_email+"-"+
       "#{restrict_email.id}"}"%></td>
                <td><%= restrict_email.blocked_email %></td>
      
    
      </tr>
          <% end %>

<%= submit_tag "Delete selected" ,:onclick => "return confirm('Are you sure?')" ,:class=>'btn btn-primary',:id=>'delete_multiple',:disabled=>true%>&nbsp;

    <% end %>
          <input type="submit" id="res_email" class="btn btn-primary "

  </tbody>
</table>
<%end%>


<div id="edit-form" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
<%=form_tag restrict_emails_path, :html => {:method => :post} do %>
 <input type="textarea" name="restrict_email_edit[blocked_email]" id="restrict_email_blocked_email_edit"  class="form-control no-border"></input>
 <div class="modal-footer">
  <%= submit_tag "submit", class: "btn-confirm btn btn-small btn-primary pull-right" %>
        </div>

<%end%>    
 </div>
      
    </div>

  </div>
</div>

<div id="delete-confirm" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
           <input type="submit" id="delete-pop-btn" class="btn-confirm  btn-primary pull-right">
     </div>
      
    </div>

  </div>
</div>

<br>

<script type="text/javascript">
$('#res_email').on("click", function () {
       var abc=[]

  $('input[name="blocked_email[]"]:checked').each(function() {
     abc.push(this.value.split('-')[0])

  });
  $('#restrict_email_blocked_email_edit').attr('value',abc.join())
  $('#edit-form').modal('show')

});
  $(':checkbox').change(function() {

     if ($('input[name="blocked_email[]"]:checked').length > 0){
       $('#delete_multiple').attr('disabled',false)  }
     else{
          $('#delete_multiple').attr('disabled',true)
     }

  //     $('input[name="blocked_email[]"]:checked').each(function() {
           
  //       $('#delete_multiple').attr('disabled',false)
  // });  

  //    $('input[name="blocked_email[]"]:checkbox:not(:checked)').each(function() {
           
  //       $('#delete_multiple').attr('disabled',true)
  // });// do stuff here. It will fire on any checkbox change

}); 

</script>

app/views/restrict_emails/new.html.erb
<h1>New Restrict Email</h1>

<%= render 'form' %>

<%= link_to 'Back', restrict_emails_path %>

app/views/restrict_emails/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_restrict_email_path(@restrict_email) %> |
<%= link_to 'Back', restrict_emails_path %>